# Player Classes
BARD = "Bard"
CLERIC = "Cleric"
DRUID = "Druid"
ENCHANTER = "Enchanter"
MAGICIAN = "Magician"
MONK = "Monk"
NECROMANCER = "Necromancer"
PALADIN = "Paladin"
RANGER = "Ranger"
ROGUE = "Rogue"
SHADOW_KNIGHT = "Shadow Knight"
SHAMAN = "Shaman"
WARRIOR = "Warrior"
WIZARD = "Wizard"

# Raid Roles
TANKS = (WARRIOR, PALADIN, SHADOW_KNIGHT)
KNIGHTS = (PALADIN, SHADOW_KNIGHT)
PRIESTS = (CLERIC, DRUID, SHAMAN)
MELEE = (BARD, MONK, RANGER, ROGUE)
CASTERS = (ENCHANTER, MAGICIAN, NECROMANCER, WIZARD)

ALL_CLASSES = set(TANKS + PRIESTS + MELEE + CASTERS)
ALL_CLASSES_RAID_IMPORTANCE = (
    WARRIOR, CLERIC, BARD,
    MAGICIAN, WIZARD, MONK,
    SHAMAN, ENCHANTER, ROGUE,
    NECROMANCER, SHADOW_KNIGHT, PALADIN,
    DRUID, RANGER
)

# Group template types
GT_GENERAL = "General"
GT_TANK = "Tank"
GT_CLERIC = "Cleric"
GT_PULL = "Pull"
