# Player Classes
BARD            = "Bard"
CLERIC          = "Cleric"
DRUID           = "Druid"
ENCHANTER       = "Enchanter"
MAGICIAN        = "Magician"
MONK            = "Monk"
NECROMANCER     = "Necromancer"
PALADIN         = "Paladin"
RANGER          = "Ranger"
ROGUE           = "Rogue"
SHADOW_KNIGHT   = "Shadow Knight"
SHAMAN          = "Shaman"
WARRIOR         = "Warrior"
WIZARD          = "Wizard"
TANKS           = (WARRIOR, PALADIN, SHADOW_KNIGHT)
KNIGHTS         = (PALADIN, SHADOW_KNIGHT)
PRIESTS         = (CLERIC, DRUID, SHAMAN)
MELEE           = (BARD, MONK, RANGER, ROGUE)
CASTERS         = (ENCHANTER, MAGICIAN, NECROMANCER, WIZARD)
