[tox]
envlist = lint,coverage
skipsdist = True

[testenv]
basepython = python3
setenv = PYTHONDONTWRITEBYTECODE=1
usedevelop = True
; envdir = {toxworkdir}/pep8
deps = -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt

[testenv:lint]
commands =
    ruff format ninjalooter/
    ruff check ninjalooter/ {posargs}

[testenv:py3]
; changedir = {envtmpdir}
commands = python -m unittest discover -v -s ninjalooter.tests

[testenv:coverage]
; changedir = {envtmpdir}
commands =
    coverage erase
    coverage run -m unittest discover -v -s ninjalooter.tests
    coverage report -m --fail-under 60
    coverage html

[testenv:build]
deps = -r{toxinidir}/requirements.txt
       pyinstaller
commands =
    python build_bootloader.py
    pyinstaller ninjalooter_py.spec