[tox]
envlist = lint,coverage

[testenv]
basepython = python3
setenv = PYTHONDONTWRITEBYTECODE=1
usedevelop = True
extras = test

[testenv:lint]
commands =
    ruff format ninjalooter/
    ruff check ninjalooter/ {posargs}

[testenv:py3]
commands = python -m unittest discover -v -b -s ninjalooter.tests

[testenv:coverage]
commands =
    coverage erase
    coverage run -m unittest discover -v -b -s ninjalooter.tests
    coverage report -m --fail-under 60
    coverage html

[testenv:build]
deps = pyinstaller
commands =
    python build_bootloader.py
    pyinstaller ninjalooter_py.spec

[testenv:app]
commands = python -m ninjalooter.cmd.run