name: tox testing

on: [pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -v -e lint,coverage
